"""
Dictionaries for receipt item name normalization.
Contains abbreviation expansions, OCR corrections, and stopwords.
"""

# Common grocery receipt abbreviations → full words
# Includes shorthand from top US retailers:
#   Costco (KS = Kirkland Signature), Walmart (GV = Great Value),
#   Kroger (KRG, SMPL TRTH = Simple Truth), Target (GG = Good & Gather),
#   Albertsons/Safeway (SIG SEL = Signature Select, O ORG = O Organics),
#   Publix (GW = Greenwise), H-E-B (HCF = Hill Country Fare),
#   Sam's Club (MM = Member's Mark), Trader Joe's (TJ = Trader Joe's),
#   Aldi (SS = Simply Nature for Aldi context), BJ's, Meijer, etc.
ABBREVIATIONS: dict[str, str] = {
    # ── Store brands / private labels ────────────────────────────────
    "KS": "Kirkland Signature",
    "KLND": "Kirkland",
    "KIRKL": "Kirkland",
    "GV": "Great Value",
    "GRTVAL": "Great Value",
    "EQ": "Equate",  # Walmart health/beauty
    "SMTRTH": "Simple Truth",
    "SMPTRH": "Simple Truth",
    "KRG": "Kroger",
    "KRGR": "Kroger",
    "PRVSEL": "Private Selection",  # Kroger premium
    "GG": "Good & Gather",  # Target
    "FVDAY": "Favorite Day",  # Target bakery/snacks
    "UPUP": "Up & Up",  # Target household
    "SIGSEL": "Signature Select",  # Albertsons/Safeway
    "OORG": "O Organics",  # Albertsons/Safeway organic
    "LCRNA": "Lucerne",  # Safeway dairy
    "LCERN": "Lucerne",
    "GW": "Greenwise",  # Publix organic
    "PBX": "Publix",
    "PUBLX": "Publix",
    "HCF": "Hill Country Fare",  # H-E-B value
    "HEB": "H-E-B",
    "CNTRL": "Central Market",  # H-E-B premium
    "MM": "Member's Mark",  # Sam's Club
    "MMBRS": "Member's Mark",
    "MMRK": "Member's Mark",
    "TJ": "Trader Joe's",
    "TRDJOE": "Trader Joe's",
    "SIMNAT": "Simply Nature",  # Aldi organic
    "CLVRVL": "Clover Valley",  # Dollar General
    "MJRBRN": "Meijer Brand",
    "MJRBST": "Meijer Best",
    "WGMNS": "Wegmans",
    "WGMN": "Wegmans",
    "SPROUT": "Sprouts",
    "365": "365",  # Whole Foods
    "WFMKT": "Whole Foods Market",
    "SHOPRT": "ShopRite",
    "FDLION": "Food Lion",
    "FNSTFD": "Finest Foods",  # BJ's
    "BRKST": "Berkley & Jensen",  # BJ's premium
    "WNCOF": "WinCo Foods",
    "STPSHP": "Stop & Shop",
    # ── Organic / diet / attribute labels ────────────────────────────
    "ORG": "Organic",
    "ORGN": "Organic",
    "ORGNC": "Organic",
    "NTRL": "Natural",
    "NATRL": "Natural",
    "NAT": "Natural",
    "FRM": "Farm",
    "PREM": "Premium",
    "SLCT": "Select",
    "SEL": "Select",
    "ORIG": "Original",
    "ORGNL": "Original",
    "CLSSC": "Classic",
    "CLN": "Clean",
    "HLTHY": "Healthy",
    "LITE": "Light",
    "XTRA": "Extra",
    "FMLY": "Family",
    "FMLYPK": "Family Pack",
    "BNSPK": "Bonus Pack",
    "VLU": "Value",
    "ECON": "Economy",
    "HMSTL": "Homestyle",
    # ── Colors / descriptors ─────────────────────────────────────────
    "YEL": "Yellow",
    "GRN": "Green",
    "RED": "Red",
    "WHT": "White",
    "BLK": "Black",
    "BLU": "Blue",
    "PNK": "Pink",
    "GLD": "Gold",
    "PRPL": "Purple",
    "BRN": "Brown",
    "YLLW": "Yellow",
    # ── Size / style ─────────────────────────────────────────────────
    "WG": "Whole Grain",
    "WHL": "Whole",
    "GRND": "Ground",
    "SHRD": "Shredded",
    "FRSH": "Fresh",
    "FRZ": "Frozen",
    "FRZN": "Frozen",
    "DELI": "Deli",
    "BKRY": "Bakery",
    "HM": "Homestyle",
    "HMSTYL": "Homestyle",
    "SM": "Small",
    "MED": "Medium",
    "LG": "Large",
    "XL": "Extra Large",
    "LT": "Light",
    "MINI": "Mini",
    "JMB": "Jumbo",
    "JUMBO": "Jumbo",
    "REG": "Regular",
    "STD": "Standard",
    "BNLS": "Boneless",
    "SKNLS": "Skinless",
    # ── Diet / health flags ──────────────────────────────────────────
    "FF": "Fat Free",
    "RF": "Reduced Fat",
    "LF": "Low Fat",
    "NF": "Non-Fat",
    "SF": "Sugar Free",
    "GF": "Gluten Free",
    "NS": "No Salt",
    "LS": "Low Sodium",
    "LSOD": "Low Sodium",
    "RDSOD": "Reduced Sodium",
    "UNSLT": "Unsalted",
    "UNSWT": "Unsweetened",
    "SWT": "Sweet",
    "KETO": "Keto",
    "PLT": "Plant",
    "PLNT": "Plant",
    "PLNTBS": "Plant Based",
    "VGAN": "Vegan",
    "VGN": "Vegan",
    "VEGN": "Vegan",
    "WHLWHT": "Whole Wheat",
    # ── Dairy ────────────────────────────────────────────────────────
    "CRM": "Cream",
    "MLK": "Milk",
    "CHEDDR": "Cheddar",
    "CHDR": "Cheddar",
    "MOZZ": "Mozzarella",
    "MZRLA": "Mozzarella",
    "PARM": "Parmesan",
    "PRMN": "Parmesan",
    "PRMGN": "Parmesan",
    "YGHRT": "Yogurt",
    "YGRT": "Yogurt",
    "YGT": "Yogurt",
    "BTR": "Butter",
    "BUTER": "Butter",
    "BTTR": "Butter",
    "MRGN": "Margarine",
    "HLFHF": "Half and Half",
    "HMILK": "Half and Half",
    "SRCM": "Sour Cream",
    "CTTG": "Cottage",
    "RICTA": "Ricotta",
    "CRMCH": "Cream Cheese",
    "PROV": "Provolone",
    "SWIS": "Swiss",
    "GOUDA": "Gouda",
    "BRIE": "Brie",
    "FETA": "Feta",
    "CHSE": "Cheese",
    # ── Flavors / sweets ─────────────────────────────────────────────
    "CHOC": "Chocolate",
    "CHCLT": "Chocolate",
    "VAN": "Vanilla",
    "STRW": "Strawberry",
    "STRWB": "Strawberry",
    "BLUEB": "Blueberry",
    "RASP": "Raspberry",
    "RSPBR": "Raspberry",
    "MANGO": "Mango",
    "COCO": "Coconut",
    "COCNT": "Coconut",
    "CINNM": "Cinnamon",
    "CINN": "Cinnamon",
    "CARAM": "Caramel",
    "CRML": "Caramel",
    "HNYMN": "Honeymoon",
    "HNY": "Honey",
    "PEACH": "Peach",
    "PCHS": "Peaches",
    "APRIC": "Apricot",
    "CHRY": "Cherry",
    "CHRRS": "Cherries",
    "CRANB": "Cranberry",
    "CRNBR": "Cranberry",
    # ── Nuts / seeds ─────────────────────────────────────────────────
    "PNT": "Peanut",
    "PNUT": "Peanut",
    "ALM": "Almond",
    "ALMND": "Almond",
    "CSH": "Cashew",
    "CSHW": "Cashew",
    "WLNT": "Walnut",
    "PECAN": "Pecan",
    "PISC": "Pistachio",
    "PSTCH": "Pistachio",
    "MCADM": "Macadamia",
    "SNFLR": "Sunflower",
    "FLXSD": "Flaxseed",
    "CHIA": "Chia",
    "SSME": "Sesame",
    # ── Meat / protein ───────────────────────────────────────────────
    "CHKN": "Chicken",
    "CHCK": "Chicken",
    "CHKTENDR": "Chicken Tender",
    "TURK": "Turkey",
    "TRKY": "Turkey",
    "BF": "Beef",
    "PRK": "Pork",
    "LAMB": "Lamb",
    "SAL": "Salmon",
    "SALMN": "Salmon",
    "SHRMP": "Shrimp",
    "TILAPIA": "Tilapia",
    "TLPA": "Tilapia",
    "BRST": "Breast",
    "THGH": "Thigh",
    "TNDR": "Tender",
    "TNDRS": "Tenders",
    "TNDRL": "Tenderloin",
    "PTTY": "Patty",
    "PTTYS": "Patties",
    "SAUS": "Sausage",
    "SSGE": "Sausage",
    "HTDG": "Hot Dog",
    "HMBRG": "Hamburger",
    "BRGR": "Burger",
    "STRLN": "Sirloin",
    "RBEYE": "Ribeye",
    "FLNK": "Flank",
    "RSTBF": "Roast Beef",
    "GRDBF": "Ground Beef",
    "GDTRKY": "Ground Turkey",
    "GDCHK": "Ground Chicken",
    "BCON": "Bacon",
    "BCN": "Bacon",
    "HAM": "Ham",
    "PRSCO": "Prosciutto",
    "PEPPR": "Pepperoni",
    "SALMI": "Salami",
    "DLMT": "Deli Meat",
    # ── Seafood ──────────────────────────────────────────────────────
    "TUNA": "Tuna",
    "COD": "Cod",
    "SWDFS": "Swordfish",
    "SCLLP": "Scallop",
    "SCLLPS": "Scallops",
    "CLAM": "Clam",
    "CLAMS": "Clams",
    "CRAB": "Crab",
    "LOBST": "Lobster",
    "MSSEL": "Mussel",
    "MSSLS": "Mussels",
    "ANCHV": "Anchovy",
    # ── Vegetables ───────────────────────────────────────────────────
    "VEG": "Vegetable",
    "VEGS": "Vegetables",
    "TOM": "Tomato",
    "TOMS": "Tomatoes",
    "TMTO": "Tomato",
    "RSTOM": "Roma Tomato",
    "POT": "Potato",
    "POTS": "Potatoes",
    "RSTPT": "Russet Potato",
    "SWPOT": "Sweet Potato",
    "ONIO": "Onion",
    "ONIN": "Onion",
    "CRRT": "Carrot",
    "CRRTS": "Carrots",
    "BROC": "Broccoli",
    "BRCC": "Broccoli",
    "BROCF": "Broccoli Florets",
    "CAUL": "Cauliflower",
    "SPIN": "Spinach",
    "SPNCH": "Spinach",
    "BBYSP": "Baby Spinach",
    "LETT": "Lettuce",
    "RMLTT": "Romaine Lettuce",
    "ROMN": "Romaine",
    "ICBRG": "Iceberg",
    "CLRY": "Celery",
    "CUCU": "Cucumber",
    "CUCM": "Cucumber",
    "PEPR": "Pepper",
    "PEPRS": "Peppers",
    "BLPPR": "Bell Pepper",
    "JLPNO": "Jalapeno",
    "JLPN": "Jalapeno",
    "HBNRO": "Habanero",
    "SRRNO": "Serrano",
    "MUSH": "Mushroom",
    "MUSHR": "Mushrooms",
    "GRLIC": "Garlic",
    "GRLC": "Garlic",
    "GNGR": "Ginger",
    "CLNTR": "Cilantro",
    "PARSL": "Parsley",
    "PRSL": "Parsley",
    "BASIL": "Basil",
    "BSL": "Basil",
    "DLWED": "Dill Weed",
    "THYME": "Thyme",
    "RSMRY": "Rosemary",
    "ASPAR": "Asparagus",
    "ASPRG": "Asparagus",
    "ZUCH": "Zucchini",
    "ZCHNI": "Zucchini",
    "SQSH": "Squash",
    "BTNUT": "Butternut",
    "EGGPL": "Eggplant",
    "ARTCH": "Artichoke",
    "KALE": "Kale",
    "CLGRN": "Collard Greens",
    "EDAMM": "Edamame",
    "BNSPR": "Bean Sprouts",
    "GRNBN": "Green Bean",
    "GRNBS": "Green Beans",
    "SNAPPS": "Snap Peas",
    "SNOWPS": "Snow Peas",
    "CORN": "Corn",
    "SWCORN": "Sweet Corn",
    "CABG": "Cabbage",
    "CBBG": "Cabbage",
    "BEET": "Beet",
    "BEETS": "Beets",
    "RADSH": "Radish",
    "TURNP": "Turnip",
    "PARLR": "Parsnip",
    "SHLLT": "Shallot",
    "LEEK": "Leek",
    "LEEKS": "Leeks",
    "FENL": "Fennel",
    "OKRA": "Okra",
    # ── Fruits ───────────────────────────────────────────────────────
    "AVCD": "Avocado",
    "AVO": "Avocado",
    "AVOS": "Avocados",
    "BANA": "Banana",
    "BANS": "Bananas",
    "MNDRN": "Mandarin",
    "MNDRS": "Mandarins",
    "APPL": "Apple",
    "APPLS": "Apples",
    "GALA": "Gala",
    "FUJI": "Fuji",
    "HNYCRSP": "Honeycrisp",
    "GRNSM": "Granny Smith",
    "ORNG": "Orange",
    "ORNGS": "Oranges",
    "NVLOR": "Navel Orange",
    "CLMTN": "Clementine",
    "CLMTS": "Clementines",
    "TNGLO": "Tangelo",
    "LMN": "Lemon",
    "LMNS": "Lemons",
    "LIME": "Lime",
    "LIMES": "Limes",
    "GRP": "Grape",
    "GRPS": "Grapes",
    "GRPFR": "Grapefruit",
    "WTRMLN": "Watermelon",
    "CNTLP": "Cantaloupe",
    "HNDEW": "Honeydew",
    "PNPPL": "Pineapple",
    "PMGRNT": "Pomegranate",
    "KWI": "Kiwi",
    "PAPYA": "Papaya",
    "PLNTN": "Plantain",
    "PLNTNS": "Plantains",
    "FIG": "Fig",
    "FIGS": "Figs",
    "PEAR": "Pear",
    "PEARS": "Pears",
    "PLUM": "Plum",
    "PLUMS": "Plums",
    "NCTRN": "Nectarine",
    "DRGFR": "Dragon Fruit",
    "LYCHEE": "Lychee",
    "PERSM": "Persimmon",
    "DTES": "Dates",
    # ── Bakery ───────────────────────────────────────────────────────
    "SGR": "Sugar",
    "FLR": "Flour",
    "BRD": "Bread",
    "WHTBRD": "White Bread",
    "WHLWB": "Whole Wheat Bread",
    "CROISS": "Croissant",
    "CRSSNT": "Croissant",
    "MFN": "Muffin",
    "MFFN": "Muffin",
    "BGEL": "Bagel",
    "BGLS": "Bagels",
    "TORTI": "Tortilla",
    "TRTLA": "Tortilla",
    "TRTLS": "Tortillas",
    "DNUTS": "Donuts",
    "DNUT": "Donut",
    "CIABTA": "Ciabatta",
    "SOURDGH": "Sourdough",
    "SRDGH": "Sourdough",
    "FOCCAC": "Focaccia",
    "BSCUT": "Biscuit",
    "BSCTS": "Biscuits",
    "RLLBNS": "Roll Buns",
    "ROLL": "Roll",
    "ROLLS": "Rolls",
    "BNRLL": "Dinner Roll",
    "HMBRBN": "Hamburger Bun",
    "HTDBN": "Hot Dog Bun",
    "PITA": "Pita",
    "NAAN": "Naan",
    "ENGL": "English",
    "ENGLMF": "English Muffin",
    # ── Condiments / pantry ──────────────────────────────────────────
    "PB": "Peanut Butter",
    "JLLY": "Jelly",
    "SCE": "Sauce",
    "KETCH": "Ketchup",
    "KTCHP": "Ketchup",
    "MSTRD": "Mustard",
    "MAYO": "Mayonnaise",
    "RNCH": "Ranch",
    "DRSG": "Dressing",
    "OL": "Oil",
    "OLVO": "Olive Oil",
    "EVOO": "Extra Virgin Olive Oil",
    "CNOIL": "Canola Oil",
    "VGOIL": "Vegetable Oil",
    "VIN": "Vinegar",
    "BALS": "Balsamic",
    "SLT": "Salt",
    "PPR": "Pepper",
    "SSNNG": "Seasoning",
    "SSNGS": "Seasoning",
    "SALSA": "Salsa",
    "HUMMS": "Hummus",
    "HMMUS": "Hummus",
    "GUAC": "Guacamole",
    "SYRP": "Syrup",
    "MPLSN": "Maple Syrup",
    "BBQSC": "BBQ Sauce",
    "SOYSAU": "Soy Sauce",
    "TERYAKI": "Teriyaki",
    "SRIRAC": "Sriracha",
    "HTSCE": "Hot Sauce",
    "WCHSTR": "Worcestershire",
    "RELSH": "Relish",
    "OLIVES": "Olives",
    "PICKL": "Pickle",
    "PCKLS": "Pickles",
    "JALPN": "Jalapeno",
    # ── Beverages ────────────────────────────────────────────────────
    "JCE": "Juice",
    "WTR": "Water",
    "SPRKL": "Sparkling",
    "SPRKLW": "Sparkling Water",
    "SLTZER": "Seltzer",
    "SODA": "Soda",
    "CFE": "Coffee",
    "CFFE": "Coffee",
    "DCAF": "Decaf",
    "KCUP": "K-Cup",
    "ESPRS": "Espresso",
    "TEA": "Tea",
    "GRNTEA": "Green Tea",
    "CMOMIL": "Chamomile",
    "LMNADE": "Lemonade",
    "LMNDE": "Lemonade",
    "SMTHY": "Smoothie",
    "KMBUCHA": "Kombucha",
    "KOMBU": "Kombucha",
    "ENRGY": "Energy",
    "SPRTS": "Sports",
    "ELCTRL": "Electrolyte",
    "COCWTR": "Coconut Water",
    "OATMLK": "Oat Milk",
    "SOYMLK": "Soy Milk",
    "ALMMLK": "Almond Milk",
    # ── Grains / pasta / cereal ──────────────────────────────────────
    "PSTA": "Pasta",
    "SPGHTI": "Spaghetti",
    "SPGHI": "Spaghetti",
    "PENNE": "Penne",
    "MACARN": "Macaroni",
    "FTTCN": "Fettuccine",
    "LSGNA": "Lasagna",
    "RAMEN": "Ramen",
    "RCE": "Rice",
    "BRWNRC": "Brown Rice",
    "JSMRC": "Jasmine Rice",
    "BSMTI": "Basmati",
    "QNA": "Quinoa",
    "CREAL": "Cereal",
    "OTML": "Oatmeal",
    "GRNLA": "Granola",
    "PANCKE": "Pancake",
    "PNCKM": "Pancake Mix",
    "WFFL": "Waffle",
    "WFFLS": "Waffles",
    # ── Cooking method / preparation ─────────────────────────────────
    "CND": "Canned",
    "CKD": "Cooked",
    "RW": "Raw",
    "RSTD": "Roasted",
    "GRLD": "Grilled",
    "SMKD": "Smoked",
    "SLCD": "Sliced",
    "DCD": "Diced",
    "MNCD": "Minced",
    "CHPPD": "Chopped",
    "CRUSH": "Crushed",
    "STMD": "Steamed",
    "SAUTD": "Sauteed",
    "BAKED": "Baked",
    "FRIED": "Fried",
    "STUFFD": "Stuffed",
    "SEASND": "Seasoned",
    "MRNTED": "Marinated",
    "BRDD": "Breaded",
    "CRSPY": "Crispy",
    # ── Frozen / prepared meals ──────────────────────────────────────
    "ICCRM": "Ice Cream",
    "PZZL": "Pizza",
    "PIZZ": "Pizza",
    "FRZPZ": "Frozen Pizza",
    "BURR": "Burrito",
    "TACO": "Taco",
    "WRAP": "Wrap",
    "SLD": "Salad",
    "SOP": "Soup",
    "STEW": "Stew",
    "CHLI": "Chili",
    "MAC": "Macaroni",
    "MACCH": "Mac and Cheese",
    "NUGGETS": "Nuggets",
    "NGTS": "Nuggets",
    "EGRLLS": "Egg Rolls",
    "POTSTR": "Potstickers",
    "FRIES": "Fries",
    "FRFRY": "French Fries",
    "ONGRNG": "Onion Rings",
    "DUMPLN": "Dumplings",
    "ETRÉE": "Entree",
    "ENTREE": "Entree",
    "DINNER": "Dinner",
    "DNR": "Dinner",
    "MEAL": "Meal",
    # ── Snacks ───────────────────────────────────────────────────────
    "SNCK": "Snack",
    "SNKS": "Snacks",
    "CHPS": "Chips",
    "TRTLCH": "Tortilla Chips",
    "CRCKR": "Cracker",
    "CRCKRS": "Crackers",
    "PRTZL": "Pretzel",
    "PRTZLS": "Pretzels",
    "CKIE": "Cookie",
    "CKIES": "Cookies",
    "POPCRN": "Popcorn",
    "PPCRN": "Popcorn",
    "TRAILM": "Trail Mix",
    "GRANBAR": "Granola Bar",
    "GRNBR": "Granola Bar",
    "PRTBAR": "Protein Bar",
    "JERKY": "Jerky",
    "BFJRKY": "Beef Jerky",
    "DRDFRT": "Dried Fruit",
    "FRTSNK": "Fruit Snack",
    "RSNBX": "Raisin Box",
    "GLDFISH": "Goldfish",
    "ANNML": "Animal Crackers",
    "GRHM": "Graham",
    "GRHMCR": "Graham Cracker",
    # ── Breakfast / eggs ─────────────────────────────────────────────
    "EGG": "Egg",
    "EGGS": "Eggs",
    "LGEGG": "Large Eggs",
    "CGEGG": "Cage Free Eggs",
    "FRNGE": "Free Range Eggs",
    # ── Household / non-food ─────────────────────────────────────────
    "TP": "Toilet Paper",
    "PAPR": "Paper",
    "TOWL": "Towel",
    "PTWL": "Paper Towel",
    "PPRTOWL": "Paper Towel",
    "NAPKN": "Napkin",
    "NAPKS": "Napkins",
    "TRSH": "Trash",
    "TRSHBG": "Trash Bag",
    "GARBG": "Garbage",
    "DTRGNT": "Detergent",
    "LNDRY": "Laundry",
    "LNDDTG": "Laundry Detergent",
    "FBRCSFTNR": "Fabric Softener",
    "DRYSHT": "Dryer Sheet",
    "CLNR": "Cleaner",
    "DSHRG": "Dish",
    "DSHSOP": "Dish Soap",
    "DSHWSH": "Dishwasher",
    "BTHRM": "Bathroom",
    "KTCHN": "Kitchen",
    "PLSTC": "Plastic",
    "ALUM": "Aluminum",
    "ALMFOL": "Aluminum Foil",
    "FOIL": "Foil",
    "BAGS": "Bags",
    "ZPLCK": "Ziplock",
    "STRG": "Storage",
    "SARAN": "Saran",
    "CLRXWP": "Clorox Wipes",
    "BLEACH": "Bleach",
    "BLCH": "Bleach",
    "SPONGE": "Sponge",
    "SPNG": "Sponge",
    "GLOVES": "Gloves",
    "GLVS": "Gloves",
    "STKS": "Sticks",
    # ── Baby / pet ───────────────────────────────────────────────────
    "DIPR": "Diaper",
    "DIPRS": "Diapers",
    "BBYFD": "Baby Food",
    "FRMLA": "Formula",
    "BBYWR": "Baby Wipes",
    "PTFOOD": "Pet Food",
    "DGFOOD": "Dog Food",
    "CTFOOD": "Cat Food",
    "CTLTTR": "Cat Litter",
    # ── Personal care ────────────────────────────────────────────────
    "SHAMP": "Shampoo",
    "SHMPO": "Shampoo",
    "CNDTN": "Conditioner",
    "BDYWSH": "Body Wash",
    "TTHPS": "Toothpaste",
    "TTPST": "Toothpaste",
    "TTHBR": "Toothbrush",
    "DEODO": "Deodorant",
    "DDORNT": "Deodorant",
    "LOTION": "Lotion",
    "LTION": "Lotion",
    "SUNSCR": "Sunscreen",
    "BNDAID": "Band-Aid",
    "TSSUE": "Tissue",
    "TSSUS": "Tissues",
    # ── Canned / jarred ──────────────────────────────────────────────
    "CNBNS": "Canned Beans",
    "BLKBN": "Black Bean",
    "GRBZO": "Garbanzo",
    "CHCKPS": "Chickpeas",
    "LENTL": "Lentil",
    "LNTLS": "Lentils",
    "KDNBN": "Kidney Bean",
    "PNTBN": "Pinto Bean",
    "CNCRN": "Canned Corn",
    "CNTOM": "Canned Tomato",
    "TMTOPST": "Tomato Paste",
    "TMPST": "Tomato Paste",
    "TMSCE": "Tomato Sauce",
    "PSTSCE": "Pasta Sauce",
    "MRNRA": "Marinara",
    "ALFRD": "Alfredo",
    "BROTH": "Broth",
    "BRTCH": "Broth Chicken",
    "STOCK": "Stock",
    "CNSOP": "Canned Soup",
    # ── Costco-specific shorthand ────────────────────────────────────
    "MEMBE": "Member",
    "ROTISS": "Rotisserie",
    "RTSRE": "Rotisserie",
    "STREETAC": "Street Taco",
    "CKNBRST": "Chicken Breast",
    "CHKNBR": "Chicken Breast",
    "PRMLOIN": "Prime Loin",
    "USDA": "USDA",
    "PRME": "Prime",
    "CHCE": "Choice",
    "ANGUS": "Angus",
}

# Common OCR misreads → correct spelling
OCR_CORRECTIONS: dict[str, str] = {
    "BUTER": "BUTTER",
    "BUTIER": "BUTTER",
    "BUITER": "BUTTER",
    "TOMTO": "TOMATO",
    "TOMATOE": "TOMATO",
    "TOMAT0": "TOMATO",
    "ONLON": "ONION",
    "0NION": "ONION",
    "QNION": "ONION",
    "CHLCKEN": "CHICKEN",
    "CHICKEH": "CHICKEN",
    "CHICHEN": "CHICKEN",
    "CHICKE": "CHICKEN",
    "LETT0CE": "LETTUCE",
    "LETFUCE": "LETTUCE",
    "LETTIJCE": "LETTUCE",
    "LETUCE": "LETTUCE",
    "BROCOLI": "BROCCOLI",
    "BROCOLLI": "BROCCOLI",
    "BROCCOII": "BROCCOLI",
    "CAULI": "CAULIFLOWER",
    "CAULIFL": "CAULIFLOWER",
    "POTAT0": "POTATO",
    "POTAIO": "POTATO",
    "POTATOE": "POTATO",
    "P0TATO": "POTATO",
    "BANAHA": "BANANA",
    "BANAÑA": "BANANA",
    "8ANANA": "BANANA",
    "SAIM0N": "SALMON",
    "SALM0N": "SALMON",
    "SAIMON": "SALMON",
    "SAIM0": "SALMON",
    "UINEGAR": "VINEGAR",
    "VLNEGAR": "VINEGAR",
    "VINEGER": "VINEGAR",
    "ORANCE": "ORANGE",
    "0RANGE": "ORANGE",
    "LEMOH": "LEMON",
    "LEM0N": "LEMON",
    "MUSTAR0": "MUSTARD",
    "MUSTARO": "MUSTARD",
    "KETCHIJP": "KETCHUP",
    "CEIIERY": "CELERY",
    "CEIERY": "CELERY",
    "YOGURI": "YOGURT",
    "Y0GURT": "YOGURT",
    "CHEES3": "CHEESE",
    "CHEASE": "CHEESE",
    "CHEEZE": "CHEESE",
    "BREAO": "BREAD",
    "8READ": "BREAD",
    "BREAL": "BREAD",
    "SUCAR": "SUGAR",
    "SUGAK": "SUGAR",
    "FL0UR": "FLOUR",
    "FLOIJR": "FLOUR",
    "AVOCAD0": "AVOCADO",
    "AVACADO": "AVOCADO",
    "GRAPEFRUII": "GRAPEFRUIT",
    "PINEAPPIE": "PINEAPPLE",
    "PLNEAPPLE": "PINEAPPLE",
    "STRAWBERY": "STRAWBERRY",
    "STRAWBRRV": "STRAWBERRY",
    "BLUEBERRV": "BLUEBERRY",
    "BLUEBERY": "BLUEBERRY",
    "RASPERRV": "RASPBERRY",
    "RASPBERY": "RASPBERRY",
    "CUCUM8ER": "CUCUMBER",
    "CUCUMBE": "CUCUMBER",
    "MUSHR00M": "MUSHROOM",
    "MUSHR0OM": "MUSHROOM",
    "ASPARAG": "ASPARAGUS",
    "ASPARAGIJS": "ASPARAGUS",
    "ZUCCHIN1": "ZUCCHINI",
    "ZUCCHNI": "ZUCCHINI",
    "TORTLLLA": "TORTILLA",
    "TORT1LLA": "TORTILLA",
    "CROISSANT": "CROISSANT",
    "CROISSNT": "CROISSANT",
    "8AGEL": "BAGEL",
    "BAGLE": "BAGEL",
    "SPAGHETT1": "SPAGHETTI",
    "SPAGHETII": "SPAGHETTI",
    "WATERMEL0N": "WATERMELON",
    "WATERMEI0N": "WATERMELON",
}

# Words to lowercase in title case (stopwords)
STOPWORDS: set[str] = {
    "a",
    "an",
    "and",
    "at",
    "by",
    "for",
    "in",
    "of",
    "on",
    "or",
    "the",
    "to",
    "with",
}

# Unit-related tokens that should stay lowercase / be reformatted
UNIT_TOKENS: dict[str, str] = {
    "OZ": "oz",
    "FL": "fl",
    "LB": "lb",
    "LBS": "lb",
    "CT": "ct",
    "PK": "pk",
    "PKG": "pkg",
    "DOZ": "doz",
    "GAL": "gal",
    "QT": "qt",
    "PT": "pt",
    "ML": "ml",
    "EA": "ea",
    "PC": "pc",
    "PCS": "pcs",
}

# Non-item keywords that indicate the line should be skipped
NON_ITEM_KEYWORDS: set[str] = {
    "subtotal",
    "sub total",
    "total",
    "tax",
    "cash",
    "credit",
    "debit",
    "visa",
    "mastercard",
    "amex",
    "discover",
    "balance",
    "change",
    "tender",
    "payment",
    "card",
    "savings",
    "coupon",
    "discount",
    "member",
    "rewards",
    "points",
    "thank you",
    "welcome",
    "receipt",
    "store",
    "cashier",
    "register",
    "transaction",
    "date",
    "time",
}
